version: '4.33.1'
services:
    frontend:
        image: antoniopapa1991/frontend
        depends_on:
            - backend
        ports:
            - 8080:8080

    backend:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - 8000:8000
        volumes:
            - .:/app
        depends_on:
            - db

    db:
        image: mysql
        environment:
            MYSQL_ROOT_PASSWORD:
            MYSQL_PASSWORD:
            MYSQL_DATABASE: laravel_api
            MYSQL_ALLOW_EMPTY_PASSWORD: true
        ports:
            - "33066:3306"
        volumes:
            - ./storage/dbdata:/var/lib/mysql
