version: '4.3'
services:
    backend:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - 8000:8000
        volumes:
            - .:/app
        depends_on:
            - db

    db:
        image: mysql
        environment:
            MYSQL_ROOT_PASSWORD:
            MYSQL_USER: root
            MYSQL_PASSWORD:
            MYSQL_DATABASE: laravel_api
        ports:
            - "3306:3306"
        volumes:
            - ./storage/dbdata:/var/lib/mysql
